### ISSUE TITLE
How to upload from a url?

### ISSUE THREAD

**Issue by kidbombay** [elixir-waffle/waffle_ecto#21]
Is there an example of phoenix form integration of how to upload an image to waffle field from a url?

**Comment by silvagustin** [comment]
Hi @kidbombay !

Did you find some solution or workaround for this? This is the only thing I found on the [docs](https://hexdocs.pm/waffle_ecto/Waffle.Ecto.Schema.html#cast_attachments/4-examples):

`cast_attachments(changeset, params, [:fetched_remote_file], allow_urls: true)`

I've tried using it but I hadn't succeed. Currently, I'm working on a workaround which consist on storing the file on a /tmp folder and then running the upload process.

Cheers.

**Comment by kidbombay** [comment]
I just do this
cast_attachments(attrs, [:banner], allow_urls: true)

Where banner is the name of your field.

**Comment by achempion** [comment]
Hi,

here is how to define a changeset

```elixir
  def url_changeset(user, params \\ :invalid) do
    user
    |> cast(params, ~w(first_name)a)
    |> cast_attachments(params, ~w(avatar)a, allow_urls: true)
    |> validate_required(:avatar)
  end
```

here is how to use it

```elixir
  test_with_mock "allow_paths => true", DummyDefinition,
    store: fn {"/path/to/my/file.png", %TestUser{}} -> {:ok, "file.png"} end do
    TestUser.path_changeset(%TestUser{}, %{"avatar" => "  /path/to/my/file.png  "})
    assert called(DummyDefinition.store({"/path/to/my/file.png", %TestUser{}}))
  end
```

Examples are taken from [test cases](https://github.com/elixir-waffle/waffle_ecto/blob/master/test/schema_test.exs#L33).
