### ISSUE TITLE
Url/delete not overridable

### ISSUE THREAD

**Issue by ah0y** [elixir-waffle/waffle_ecto#49]
waffle_ecto is an awesome library! However I'm running into issues with overriding url/3 and delete/1 in my definition 

I've opened https://github.com/elixir-waffle/waffle_ecto/pull/50 and verified that I can now override url. Is what I'm doing correct? I have no idea as I've never done any meta-programming before.

**Comment by achempion** [comment]
Hi, Abe

What is your use case for overriding the url/delete functions? Will just creating a function with a different name work?

**Comment by ah0y** [comment]
On second thought I don't actually need to override url/delete and can just make new functions. Thanks for the suggestion!
